export const LEAD_CHANNELS = [
  { id: 'showroom', name: '展厅', shortName: '展厅', icon: '🏪', desc: '线下到店、老客转介绍和自然渠道，质量稳定。', walkInFactor: 1.05 },
  { id: 'sourcing', name: '采买', shortName: '采买', icon: '🧲', desc: '投流和外部采买线索，量大但需要DCC筛选。', walkInFactor: 0.88 },
  { id: 'livestream', name: '直播', shortName: '直播', icon: '🎙️', desc: '主播配合投流带来的线上意向客户，受主播能力影响。', walkInFactor: 1.0 },
  { id: 'autoshow', name: '车展', shortName: '车展', icon: '🎪', desc: '车展活动和区域资源带来的集中线索，短期转化更强。', walkInFactor: 1.18 },
];

export const EMPTY_LEAD_CHANNELS = LEAD_CHANNELS.reduce((acc, channel) => ({ ...acc, [channel.id]: 0 }), {});

export const CUSTOMER_ARCHETYPES = [
  { id: 'price', name: '价格敏感', desc: '手里攥着竞品报价，核心诉求是便宜。', priceFocus: 1.0, financeBias: 0.1, tradeInBias: 0.1 },
  { id: 'finance', name: '金融意向强', desc: '在意月供和首付，对金融方案接受度高。', priceFocus: 0.55, financeBias: 0.55, tradeInBias: 0.08 },
  { id: 'tradein', name: '置换客户', desc: '旧车想一起处理，置换补贴会明显影响决策。', priceFocus: 0.65, financeBias: 0.15, tradeInBias: 0.6 },
  { id: 'comparison', name: '竞品比价中', desc: '宝马奔驰都看过，需要给出足够确定的购买理由。', priceFocus: 0.8, financeBias: 0.2, tradeInBias: 0.12 },
  { id: 'urgent', name: '月底急提车', desc: '想尽快开走现车，价格不是唯一变量。', priceFocus: 0.45, financeBias: 0.18, tradeInBias: 0.08 },
];

export const CUSTOMER_NAMES = ['陈先生', '林女士', '周总', '王先生', '赵女士', '刘先生', '张经理', '许女士', '何先生', '马女士'];

export const MARKETING_ACTIVITIES = [
  {
    id: 'digital_ad',
    name: '线索采买',
    icon: '🧲',
    cost: 2000,
    costType: 'daily',
    budgetKey: 'leadPurchaseBudget',
    duration: 0,
    effect: 'leads',
    channel: 'sourcing',
    description: '每日投入采买预算，直接增加采买线索数量，约¥50/条',
    color: 'from-blue-50 to-indigo-50 border-blue-200',
    btnColor: 'bg-blue-600 hover:bg-blue-500',
  },
  {
    id: 'livestream_ad',
    name: '直播投流',
    icon: '🎙️',
    cost: 0,
    costType: 'daily',
    budgetKey: 'livestreamBudget',
    duration: 0,
    effect: 'livestream_leads',
    channel: 'livestream',
    description: '每日投入直播流量预算，配合主播数量和能力产出直播线索',
    color: 'from-fuchsia-50 to-pink-50 border-fuchsia-200',
    btnColor: 'bg-fuchsia-600 hover:bg-fuchsia-500',
  },
  {
    id: 'gift_event',
    name: '到店礼活动',
    icon: '🎁',
    cost: 8000,
    costType: 'oneTime',
    duration: 3,
    effect: 'dcc_walkin',
    effectValue: 0.08,
    channel: 'showroom',
    description: '到店送精美伴手礼，展厅线索邀约到店率+8%，持续3天',
    color: 'from-amber-50 to-orange-50 border-amber-200',
    btnColor: 'bg-amber-600 hover:bg-amber-500',
  },
  {
    id: 'auto_show',
    name: '周末车展',
    icon: '🎪',
    cost: 25000,
    costType: 'oneTime',
    duration: 1,
    effect: 'natural_walkin',
    effectValue: 8,
    channel: 'autoshow',
    leadBonus: 25,
    description: '举办品牌车展活动，当日自然客流+8批，车展线索+25，转化率+5%',
    effect2: 'conversion',
    effect2Value: 0.05,
    color: 'from-red-50 to-pink-50 border-red-200',
    btnColor: 'bg-red-600 hover:bg-red-500',
  },
  {
    id: 'flash_sale',
    name: '限时促销',
    icon: '⚡',
    cost: 12000,
    costType: 'oneTime',
    duration: 2,
    effect: 'conversion',
    effectValue: 0.10,
    channel: 'showroom',
    description: '限时特价+赠精品套餐，销售转化率+10%，持续2天',
    color: 'from-purple-50 to-fuchsia-50 border-purple-200',
    btnColor: 'bg-purple-600 hover:bg-purple-500',
  },
  {
    id: 'customer_care',
    name: '老客维系',
    icon: '🤝',
    cost: 5000,
    costType: 'oneTime',
    duration: 0,
    effect: 'recover',
    effectValue: 15,
    channel: 'showroom',
    description: 'DCC回访战败客户，一次性回收15条展厅线索进入跟进池',
    color: 'from-emerald-50 to-teal-50 border-emerald-200',
    btnColor: 'bg-emerald-600 hover:bg-emerald-500',
  },
];
