export const OPERATING_EVENT_DIFFICULTY = {
  rookie: { chanceMultiplier: 0.65, severityMultiplier: 0.75, maxDailyEvents: 1, responseCostMultiplier: 0.82, successModifier: 0.08, expiryGraceDays: 4 },
  standard: { chanceMultiplier: 1, severityMultiplier: 1, maxDailyEvents: 1, responseCostMultiplier: 1, successModifier: 0, expiryGraceDays: 3 },
  hardcore: { chanceMultiplier: 1.35, severityMultiplier: 1.22, maxDailyEvents: 2, responseCostMultiplier: 1.18, successModifier: -0.08, expiryGraceDays: 2 },
};

export const OPERATING_EVENT_RESOLUTION_OPTIONS = {
  risk: [
    {
      id: 'contain_now',
      title: '快速止损',
      description: '立刻投入现金和管理注意力，尽量把负面影响压到最低。',
      successChance: 0.86,
      eventEffectMultiplier: 0.25,
      failureEventEffectMultiplier: 0.7,
      effects: { cashDelta: -9000, csiDelta: 0.4 },
    },
    {
      id: 'process_fix',
      title: '流程整改',
      description: '用较低成本做内部整改，结果更依赖团队执行。',
      successChance: 0.68,
      eventEffectMultiplier: 0.45,
      failureEventEffectMultiplier: 0.9,
      effects: { cashDelta: -3500 },
    },
    {
      id: 'delay_and_watch',
      title: '暂缓观察',
      description: '不立刻投入资源，短期省钱，但失败时更接近原始风险。',
      successChance: 0.38,
      eventEffectMultiplier: 0.75,
      failureEventEffectMultiplier: 1.15,
      effects: {},
    },
  ],
  opportunity: [
    {
      id: 'commit_resources',
      title: '加码承接',
      description: '投入小额预算和人力，把机会转成更高质量线索或收益。',
      successChance: 0.84,
      eventEffectMultiplier: 1.25,
      failureEventEffectMultiplier: 0.65,
      effects: { cashDelta: -5000 },
    },
    {
      id: 'focus_team',
      title: '团队跟进',
      description: '让现有团队承接机会，成本较低，效果相对稳健。',
      successChance: 0.66,
      eventEffectMultiplier: 0.9,
      failureEventEffectMultiplier: 0.45,
      effects: { cashDelta: -1800 },
    },
    {
      id: 'passive_receive',
      title: '顺势承接',
      description: '不追加资源，只接住自然流量，收益有限但没有额外现金压力。',
      successChance: 0.44,
      eventEffectMultiplier: 0.55,
      failureEventEffectMultiplier: 0.15,
      effects: {},
    },
  ],
};

export const OPERATING_EVENT_TYPES = [
  {
    id: 'weekend_group_visit',
    title: '高意向团购客户到店',
    from: '销售运营部',
    tone: 'opportunity',
    baseChance: 0.045,
    minDay: 3,
    tags: ['lead', 'sales'],
    condition: { minSalesCount: 1 },
    effects: {
      leadChannels: { showroom: 8 },
      monthlyStats: { leads: 8 },
    },
    log: '一批高意向团购客户临时到店，新增8条展厅线索。销售需要尽快承接。',
    body: '销售运营部收到老客户转介绍团购需求，今天会集中进店比价。若库存结构和接待能力跟得上，这是一次快速成交机会。',
  },
  {
    id: 'bank_credit_recheck',
    title: '银行临时授信复核',
    from: '合作银行',
    tone: 'risk',
    baseChance: 0.035,
    minDay: 8,
    tags: ['finance', 'credit'],
    condition: { creditUsageGte: 0.72 },
    effects: {
      creditLimitDelta: -180000,
      financeCost: 3500,
    },
    log: '合作银行临时复核库存融资，压降部分授信并收取复核服务费。',
    body: '银行注意到库存融资使用率偏高，要求门店降低资金占用。短期内可用授信减少，财务费用增加。',
  },
  {
    id: 'customer_public_review',
    title: '客户负面点评扩散',
    from: '客户关系中心',
    tone: 'risk',
    baseChance: 0.04,
    minDay: 5,
    tags: ['csi', 'brand'],
    condition: { csiBelow: 84 },
    effects: {
      csiDelta: -1.8,
      leadChannels: { showroom: -3 },
    },
    log: '客户负面点评扩散，CSI承压，展厅自然线索减少。',
    body: '客户关系中心监测到交付、价格或售后体验相关负面反馈开始扩散。建议尽快处理客诉、稳定交付承诺。',
  },
  {
    id: 'manufacturer_bonus_window',
    title: '厂家短促支持窗口',
    from: '厂家商务部',
    tone: 'opportunity',
    baseChance: 0.03,
    minDay: 10,
    tags: ['manufacturer', 'rebate'],
    condition: { targetProgressBelow: 0.72 },
    effects: {
      rebatePoolDelta: 26000,
    },
    log: '厂家释放短促支持窗口，返利池获得一次性补强。',
    body: '厂家商务部为了拉动区域销量，给到一笔短促支持。若本月能继续推进真实成交，月底兑现压力会小一些。',
  },
  {
    id: 'aged_stock_inspection',
    title: '长库龄车辆专项检查',
    from: '厂家区域经理',
    tone: 'risk',
    baseChance: 0.038,
    minDay: 12,
    tags: ['inventory', 'manufacturer'],
    condition: { agedInventoryGte: 3 },
    effects: {
      cashDelta: -12000,
      manufacturerPenalty: 12000,
    },
    log: '厂家区域经理抽查长库龄车辆，产生整改与仓储形象成本。',
    body: '厂家区域经理认为长库龄车辆影响展厅形象，要求门店整改陈列、更新物料，并提交清库计划。',
  },
  {
    id: 'local_media_visit',
    title: '本地媒体探店机会',
    from: '市场部',
    tone: 'opportunity',
    baseChance: 0.025,
    minDay: 6,
    tags: ['marketing', 'brand'],
    condition: { csiAbove: 88 },
    effects: {
      leadChannels: { livestream: 6, showroom: 4 },
      monthlyStats: { leads: 10 },
    },
    log: '本地媒体探店带来曝光，直播和展厅线索增加。',
    body: '本地汽车媒体愿意做一次门店探访。门店口碑较稳时，这类曝光会带来更高质量线索。',
  },
];
