export const SALES_OPPORTUNITY_LIMITS = {
  maxActive: 18,
  maxHistory: 80,
  staleAfterDays: 0,
};

export const SALES_OPPORTUNITY_DIFFICULTY = {
  rookie: {
    generationMultiplier: 1.22,
    dailyLimit: 5,
    qualityModifier: 8,
    actionSuccessModifier: 0.08,
    costMultiplier: 0.85,
    expiryPressure: 1,
  },
  standard: {
    generationMultiplier: 1,
    dailyLimit: 4,
    qualityModifier: 0,
    actionSuccessModifier: 0,
    costMultiplier: 1,
    expiryPressure: 0,
  },
  hardcore: {
    generationMultiplier: 0.82,
    dailyLimit: 3,
    qualityModifier: -7,
    actionSuccessModifier: -0.08,
    costMultiplier: 1.18,
    expiryPressure: -1,
  },
};

export const SALES_OPPORTUNITY_TYPES = {
  lead: {
    title: '新线索筛选',
    description: '营销漏斗带来的新线索，需要先确认预算、车型和到店意愿。',
    sourceName: '漏斗营销',
    status: 'new',
    baseHeat: 46,
    baseTrust: 42,
    dueInDays: 3,
    scoreWeight: 1,
    actions: ['qualify', 'followUp', 'discard'],
    ownerRoles: ['dcc', 'sales'],
  },
  test_drive: {
    title: '试驾邀约',
    description: '客户已有到店或体验意愿，适合优先安排试驾。',
    sourceName: '展厅接待',
    status: 'qualified',
    baseHeat: 58,
    baseTrust: 50,
    dueInDays: 2,
    scoreWeight: 1.05,
    actions: ['inviteTestDrive', 'quote', 'discard'],
    ownerRoles: ['sales', 'streamer'],
  },
  quote: {
    title: '报价推进',
    description: '客户接近谈判，需要给出清晰成交价、月供和交付方案。',
    sourceName: '重点客户',
    status: 'quoted',
    baseHeat: 66,
    baseTrust: 56,
    dueInDays: 2,
    scoreWeight: 1.12,
    actions: ['quote', 'close', 'discard'],
    ownerRoles: ['sales'],
  },
  follow_up: {
    title: '客户回访',
    description: '成交或战败客户进入后续经营窗口，适合转介绍、复活或续保触达。',
    sourceName: '客户中心',
    status: 'active',
    baseHeat: 52,
    baseTrust: 62,
    dueInDays: 3,
    scoreWeight: 1,
    actions: ['followUp', 'quote', 'discard'],
    ownerRoles: ['service', 'sales'],
  },
  risk: {
    title: '流失风险',
    description: '客户、报价或库存存在流失风险，今天不处理会快速过期。',
    sourceName: '销售预警',
    status: 'at_risk',
    baseHeat: 35,
    baseTrust: 34,
    dueInDays: 1,
    scoreWeight: 1.18,
    actions: ['followUp', 'quote', 'discard'],
    ownerRoles: ['sales', 'dcc'],
  },
};

export const SALES_OPPORTUNITY_OWNER_RULES = {
  skillWeight: 0.58,
  stressWeight: -0.22,
  loyaltyWeight: 0.08,
  workloadPenalty: 6,
  retainedBonus: 4,
  fallbackRoleOrder: ['sales', 'dcc', 'service', 'streamer'],
  traitActionBonus: {
    qualify: { diligent: 0.03, talker: 0.05, rookie: -0.02 },
    inviteTestDrive: { relationship: 0.04, product: 0.04, traffic: 0.02 },
    quote: { price_killer: 0.06, finance: 0.04, relationship: 0.03 },
    followUp: { relationship: 0.06, patient: 0.05, callback: 0.04, process: 0.03 },
    close: { price_killer: 0.04, finance: 0.04, relationship: 0.03, rookie: -0.02 },
    discard: {},
  },
};

export const SALES_OPPORTUNITY_OWNER_FEEDBACK = {
  success: { xp: 5, stress: 1.2, loyalty: 0.35 },
  failed: { xp: 2, stress: 2.2, loyalty: -0.2 },
  close: { xp: 8, stress: 1.8, loyalty: 0.5 },
  discard: { xp: 0.5, stress: -0.6, loyalty: 0 },
};

export const SALES_OPPORTUNITY_ACTIONS = {
  qualify: {
    id: 'qualify',
    title: '资格判断',
    description: '确认预算、车型和购车时间，过滤低质量线索。',
    cost: 0,
    fromStatuses: ['new', 'at_risk', 'active'],
    successBase: 0.82,
    nextStatus: 'qualified',
    heatDelta: 8,
    trustDelta: 6,
    dueDelta: 2,
    terminal: false,
    metadata: { logType: 'info', inboxTag: 'qualified' },
  },
  inviteTestDrive: {
    id: 'inviteTestDrive',
    title: '邀约试驾',
    description: '安排试驾车、顾问接待和到店动线，提升客户购买冲动。',
    cost: 600,
    fromStatuses: ['new', 'qualified', 'active', 'at_risk'],
    successBase: 0.76,
    nextStatus: 'test_drive',
    heatDelta: 16,
    trustDelta: 8,
    dueDelta: 2,
    terminal: false,
    metadata: { logType: 'success', inboxTag: 'test_drive' },
  },
  quote: {
    id: 'quote',
    title: '给出报价',
    description: '给客户一版清晰的成交价、月供和交付方案。',
    cost: 0,
    fromStatuses: ['qualified', 'test_drive', 'active', 'at_risk', 'quoted'],
    successBase: 0.68,
    nextStatus: 'quoted',
    heatDelta: 10,
    trustDelta: 4,
    dueDelta: 1,
    terminal: false,
    metadata: { logType: 'info', inboxTag: 'quote' },
  },
  followUp: {
    id: 'followUp',
    title: '重点跟进',
    description: '让销售顾问进行一次明确触达，修复犹豫点。',
    cost: 300,
    fromStatuses: ['new', 'qualified', 'test_drive', 'quoted', 'active', 'at_risk'],
    successBase: 0.7,
    nextStatus: 'active',
    heatDelta: 9,
    trustDelta: 8,
    dueDelta: 2,
    terminal: false,
    metadata: { logType: 'info', inboxTag: 'follow_up' },
  },
  close: {
    id: 'close',
    title: '推进成交',
    description: '把报价机会推向成交谈判，成功后计入机会历史并等待成交系统承接。',
    cost: 0,
    fromStatuses: ['quoted', 'test_drive', 'qualified'],
    successBase: 0.58,
    nextStatus: 'closed',
    heatDelta: 0,
    trustDelta: 0,
    dueDelta: 0,
    terminal: true,
    metadata: { logType: 'success', inboxTag: 'close', revenueIntent: true },
  },
  discard: {
    id: 'discard',
    title: '放弃机会',
    description: '关闭低质量或明显无利润机会，释放销售注意力。',
    cost: 0,
    fromStatuses: ['new', 'qualified', 'test_drive', 'quoted', 'active', 'at_risk'],
    successBase: 1,
    nextStatus: 'discarded',
    heatDelta: 0,
    trustDelta: 0,
    dueDelta: 0,
    terminal: true,
    metadata: { logType: 'info', inboxTag: 'discard' },
  },
};

export const SALES_OPPORTUNITY_TYPE_META = SALES_OPPORTUNITY_TYPES;
