export const STORY_EVENT_VERSION = 1;

export const STORY_EVENT_CHAINS = [
  {
    id: 'investor_pressure',
    title: '投资人施压',
    source: '投资人办公室',
    tags: ['investor', 'finance', 'monthly-review'],
    cadence: 'monthly',
    cooldownDays: 18,
    expiresInDays: 30,
    participants: ['投资人代表', '总经理', '财务经理'],
    suggestedActions: ['准备月度复盘', '压缩非必要开支', '优先处理现金和CSI短板'],
    effectsPreview: ['可能触发订车限制', '可能降低预算授权', '连续差评会放大解聘风险'],
    stages: [
      {
        id: 'attention',
        label: '关注',
        severity: 'warning',
        minScore: 42,
        title: '投资人要求提交经营说明',
        summary: '销量节奏、现金或CSI出现短板，投资人开始要求管理层解释本月经营质量。',
      },
      {
        id: 'pressure',
        label: '施压',
        severity: 'high',
        minScore: 66,
        title: '投资人要求压缩预算',
        summary: '经营评分承压，投资人倾向先收紧授权，再观察下月能否扭转。',
      },
      {
        id: 'ultimatum',
        label: '最后通牒',
        severity: 'critical',
        minScore: 84,
        title: '董事会准备问责总经理',
        summary: '连续差评、现金吃紧或亏损扩大，投资人已把经营权稳定性列为核心议题。',
      },
    ],
  },
  {
    id: 'manufacturer_stock_pressure',
    title: '厂家压库',
    source: '厂家商务部',
    tags: ['manufacturer', 'inventory', 'rebate'],
    cadence: 'monthly',
    cooldownDays: 16,
    expiresInDays: 24,
    participants: ['厂家区域经理', '销售经理', '库存管理员'],
    suggestedActions: ['评估下月订车节奏', '申请长库龄补贴', '控制库龄与展厅结构'],
    effectsPreview: ['可能影响返利沟通', '可能增加订车压力', '库存结构会影响月评观感'],
    stages: [
      {
        id: 'quota_hint',
        label: '暗示',
        severity: 'info',
        minScore: 40,
        title: '厂家提醒关注配车节奏',
        summary: '厂家开始强调区域份额和车型结构，希望门店保持足够库存声量。',
      },
      {
        id: 'quota_push',
        label: '压库',
        severity: 'warning',
        minScore: 62,
        title: '厂家提出下月配车要求',
        summary: '库存、目标和商务政策形成压力，厂家希望用更多配车换取返利与资源支持。',
      },
      {
        id: 'authorization_risk',
        label: '授权风险',
        severity: 'high',
        minScore: 82,
        title: '厂家警告授权与返利风险',
        summary: '长期未达目标或库存结构失衡，厂家开始把商务支持与授权评价挂钩。',
      },
    ],
  },
  {
    id: 'bank_credit_pullback',
    title: '银行抽贷',
    source: '合作银行',
    tags: ['bank', 'credit', 'cashflow'],
    cadence: 'daily',
    cooldownDays: 12,
    expiresInDays: 18,
    participants: ['银行客户经理', '财务经理', '总经理'],
    suggestedActions: ['降低库存融资占用', '兑付逾期汇票', '提高现金安全垫'],
    effectsPreview: ['可能下调库存融资授信', '可能提高风控关注', '逾期汇票会恶化银行信用'],
    stages: [
      {
        id: 'watchlist',
        label: '观察名单',
        severity: 'warning',
        minScore: 45,
        title: '银行把门店列入观察名单',
        summary: '负债率或现金覆盖已接近风控线，银行开始要求补充经营解释。',
      },
      {
        id: 'credit_review',
        label: '授信复核',
        severity: 'high',
        minScore: 68,
        title: '银行启动授信复核',
        summary: '融资占用、现金缺口或汇票逾期叠加，银行倾向重新核算授信额度。',
      },
      {
        id: 'pullback_warning',
        label: '抽贷预警',
        severity: 'critical',
        minScore: 86,
        title: '银行发出抽贷预警',
        summary: '资金链风险已被银行升级，若月底数据没有改善，授信很可能被压缩。',
      },
    ],
  },
  {
    id: 'competitor_poaching',
    title: '竞品挖人',
    source: '市场情报组',
    tags: ['competitor', 'staff', 'poaching'],
    cadence: 'weekly',
    cooldownDays: 14,
    expiresInDays: 21,
    participants: ['竞品门店', '销售骨干', '人事负责人'],
    suggestedActions: ['识别高风险骨干', '安排留任津贴', '降低高压岗位负荷'],
    effectsPreview: ['可能提高核心员工流失概率', '竞品活动期挖人更频繁', '骨干离开会削弱成交能力'],
    stages: [
      {
        id: 'headhunt_ping',
        label: '接触',
        severity: 'info',
        minScore: 40,
        title: '竞品开始接触一线骨干',
        summary: '同城竞品活动升温，能力较强且压力偏高的员工更容易收到试探邀约。',
      },
      {
        id: 'offer',
        label: '报价',
        severity: 'warning',
        minScore: 64,
        title: '竞品给核心员工开出报价',
        summary: '销售或售后骨干已经进入竞品视野，团队稳定性开始影响经营节奏。',
      },
      {
        id: 'team_raid',
        label: '团队挖角',
        severity: 'high',
        minScore: 82,
        title: '竞品准备成组挖角',
        summary: '多名高能力员工同时承压，竞品可能借价格战或活动窗口成组挖人。',
      },
    ],
  },
  {
    id: 'customer_sentiment',
    title: '客户舆情',
    source: '客户关系中心',
    tags: ['customer', 'csi', 'complaint'],
    cadence: 'daily',
    cooldownDays: 10,
    expiresInDays: 16,
    participants: ['客户关系中心', '销售顾问', '售后服务经理'],
    suggestedActions: ['优先处理投诉', '复盘交付承诺', '控制低价强收带来的CSI损伤'],
    effectsPreview: ['可能拉低CSI', '可能影响返利系数', '可能造成自然客流转化下滑'],
    stages: [
      {
        id: 'noise',
        label: '噪声',
        severity: 'info',
        minScore: 38,
        title: '客户负面反馈开始增多',
        summary: '交付、价格或售后等待体验出现波动，客户关系中心建议提前干预。',
      },
      {
        id: 'public_pressure',
        label: '扩散',
        severity: 'warning',
        minScore: 62,
        title: '客户舆情有扩散迹象',
        summary: 'CSI下滑和投诉累积正在影响口碑，门店需要主动修复关键客户体验。',
      },
      {
        id: 'brand_risk',
        label: '品牌风险',
        severity: 'high',
        minScore: 82,
        title: '厂家关注客户舆情风险',
        summary: '低CSI和投诉叠加，厂家与投资人都会把口碑列为本月重点风险。',
      },
    ],
  },
  {
    id: 'staff_turnover',
    title: '员工离职',
    source: '人事负责人',
    tags: ['staff', 'turnover', 'morale'],
    cadence: 'weekly',
    cooldownDays: 12,
    expiresInDays: 18,
    participants: ['人事负责人', '部门经理', '高风险员工'],
    suggestedActions: ['降低压力峰值', '给核心员工留任津贴', '补招薄弱岗位'],
    effectsPreview: ['可能导致人员流失', '岗位空缺会限制客流承接', '团队士气会影响后续经营'],
    stages: [
      {
        id: 'fatigue',
        label: '疲态',
        severity: 'info',
        minScore: 36,
        title: '团队疲态开始显现',
        summary: '员工压力和低忠诚信号变多，需要在人手、薪酬或排班上提前缓冲。',
      },
      {
        id: 'resignation_risk',
        label: '离职风险',
        severity: 'warning',
        minScore: 60,
        title: '核心岗位出现离职风险',
        summary: '部分员工压力高、忠诚低或未被留任，离职风险已进入管理层视野。',
      },
      {
        id: 'attrition_wave',
        label: '流失潮',
        severity: 'high',
        minScore: 80,
        title: '团队可能出现集中流失',
        summary: '高压和低忠诚叠加，若不干预，多个岗位可能同时出现人员缺口。',
      },
    ],
  },
];

export const STORY_EVENT_CHAIN_BY_ID = STORY_EVENT_CHAINS.reduce((map, chain) => ({
  ...map,
  [chain.id]: chain,
}), {});
