import { CAR_MODELS } from '../game/config/vehicles.js';
import { buildAutoSaveData, buildAutoSaveGameState } from '../game/state/autoSave.js';
import { rotateAutoSaveBackups, writeSaveSlots } from '../game/state/saveSlots.js';

export function writeDailyAutoSave({
  activeMarketSize,
  activeScenario,
  afterSales,
  approvalCases,
  competitors,
  csi,
  customerLifecycle,
  customerDeals,
  salesOpportunities,
  dailyLedger,
  dailyStats,
  day,
  dealerRegionId,
  difficultyMode,
  dismissedByInvestor,
  drafts,
  endingSummary,
  facility,
  feedback,
  finance,
  gameState,
  getSaveSlots,
  gmWealth,
  inboxItems,
  insuranceRenewals,
  inventory,
  investorProfileId,
  investorRelations,
  isFreeScenario,
  logs,
  managerInbox,
  manufacturerPolicy,
  marketEnvironment,
  marketPrices,
  marketing,
  modelPriceOverrides,
  operatingEvents,
  pendingOrders,
  scenarioDurationDays,
  scenarioId,
  soldVehicles,
  storyState,
  staffStoryMemory,
  staff,
  strategy,
  testDriveCars,
  todayLedger,
  tutorial,
  usedCarShowroom,
  usedCars,
  virtualSales,
  monthlyStats,
}) {
  try {
    const newGameState = buildAutoSaveGameState({
      dismissedByInvestor,
      isFreeScenario,
      absoluteDay: day + 1,
      scenarioDurationDays,
      gameState,
      finance,
      activeScenario,
      investorRelations,
      feedback,
      assetContext: {
        finance,
        inventory,
        usedCars,
        carModels: CAR_MODELS,
        usedCarShowroom,
        drafts,
        gmWealth,
      },
    });
    const autoSaveData = buildAutoSaveData({
      gameState: newGameState,
      day: day + 1,
      dealerRegionId,
      marketSizeId: activeMarketSize.id,
      investorProfileId,
      investorRelations,
      finance,
      drafts,
      gmWealth,
      virtualSales,
      competitors,
      strategy,
      marketPrices,
      modelPriceOverrides,
      marketEnvironment,
      manufacturerPolicy,
      marketing,
      staff,
      afterSales,
      usedCarShowroom,
      usedCars,
      testDriveCars,
      csi,
      customerLifecycle,
      insuranceRenewals,
      soldVehicles,
      monthlyStats,
      operatingEvents,
      facility,
      inventory,
      pendingOrders,
      dailyStats,
      dailyLedger: [...dailyLedger, { day: day + 1, items: todayLedger }],
      managerInbox: [...managerInbox, ...inboxItems],
      approvalCases,
      customerDeals,
      salesOpportunities,
      feedback,
      storyState,
      staffStoryMemory,
      difficultyMode,
      scenarioId,
      tutorial,
      endingSummary,
      logs,
    });
    const allSlots = rotateAutoSaveBackups(getSaveSlots());
    allSlots.slots.auto = autoSaveData;
    writeSaveSlots(allSlots);
  } catch (_e) {
    // 自动存档失败静默处理
  }
}
