import { createInitialOrderForm } from '../game/state/initialState.js';
import { buildManualSaveData, normalizeLoadedSaveData } from '../game/state/saveData.js';

export function useSaveDataBridge({
  activeMarketSize,
  afterSales,
  approvalCases,
  competitors,
  csi,
  customerLifecycle,
  customerDeals,
  salesOpportunities,
  dailyLedger,
  dailyStats,
  day,
  dealerRegionId,
  difficultyMode,
  drafts,
  endingSummary,
  facility,
  feedback,
  finance,
  gameState,
  gmWealth,
  insuranceRenewals,
  inventory,
  investorProfileId,
  investorRelations,
  logs,
  managerInbox,
  manufacturerPolicy,
  marketEnvironment,
  marketPrices,
  marketing,
  modelPriceOverrides,
  monthlyStats,
  operatingEvents,
  pendingOrders,
  scenarioId,
  setActiveTab,
  setAfterSales,
  setApprovalCases,
  setCompetitors,
  setCsi,
  setCustomerLifecycle,
  setCustomerDeals,
  setSalesOpportunities,
  setDailyLedger,
  setDailyStats,
  setDay,
  setDealerRegionId,
  setDifficultyMode,
  setDrafts,
  setEndingModalDismissed,
  setEndingSummary,
  setExpandedInboxIds,
  setFacility,
  setFeedback,
  setFinance,
  setFinanceReportView,
  setGameState,
  setGmWealth,
  setInboxFilter,
  setInsuranceRenewals,
  setInventory,
  setInvestorProfileId,
  setInvestorRelations,
  setLogs,
  setManagerInbox,
  setManufacturerPolicy,
  setMarketEnvironment,
  setMarketPrices,
  setMarketSizeId,
  setMarketing,
  setModelPriceOverrides,
  setMonthlyStats,
  setMonthlySummaryModal,
  setOrderForm,
  setOperatingEvents,
  setPendingOrders,
  setReadInboxIds,
  setScenarioId,
  setSelectedInboxDay,
  setSelectedLogDay,
  setShowBriefingModal,
  setShowInboxModal,
  setSoldVehicles,
  setStoryState,
  setStaffStoryMemory,
  setStaff,
  setStrategy,
  setTestDriveCars,
  setTutorial,
  setUsedCars,
  setUsedCarShowroom,
  setVirtualSales,
  soldVehicles,
  storyState,
  staffStoryMemory,
  staff,
  strategy,
  testDriveCars,
  tutorial,
  usedCars,
  usedCarShowroom,
  virtualSales,
}) {
  const buildSaveData = () => buildManualSaveData({
    gameState,
    day,
    dealerRegionId,
    marketSizeId: activeMarketSize.id,
    investorProfileId,
    difficultyMode,
    scenarioId,
    tutorial,
    endingSummary,
    investorRelations,
    finance,
    drafts,
    gmWealth,
    virtualSales,
    competitors,
    strategy,
    marketPrices,
    modelPriceOverrides,
    marketEnvironment,
    manufacturerPolicy,
    marketing,
    staff,
    afterSales,
    usedCarShowroom,
    usedCars,
    testDriveCars,
    csi,
    customerLifecycle,
    insuranceRenewals,
    soldVehicles,
    monthlyStats,
    operatingEvents,
    facility,
    inventory,
    pendingOrders,
    dailyStats,
    dailyLedger,
    managerInbox,
    approvalCases,
    customerDeals,
    salesOpportunities,
    feedback,
    storyState,
    staffStoryMemory,
    logs,
  });

  const applySaveData = (saveData) => {
    const loaded = normalizeLoadedSaveData(saveData);
    setGameState(loaded.gameState);
    setDealerRegionId(loaded.dealerRegionId);
    setInvestorProfileId(loaded.investorProfileId);
    setMarketSizeId(loaded.marketSizeId);
    setDifficultyMode(loaded.difficultyMode);
    setScenarioId(loaded.scenarioId);
    setTutorial(loaded.tutorial);
    setEndingSummary(loaded.endingSummary);
    setEndingModalDismissed(false);
    setInvestorRelations(loaded.investorRelations);
    setDay(loaded.day);
    setFinance(loaded.finance);
    setDrafts(loaded.drafts);
    setGmWealth(loaded.gmWealth);
    setVirtualSales(loaded.virtualSales);
    setCompetitors(loaded.competitors);
    setStrategy(loaded.strategy);
    setMarketPrices(loaded.marketPrices);
    setModelPriceOverrides(loaded.modelPriceOverrides);
    setMarketEnvironment(loaded.marketEnvironment);
    setManufacturerPolicy(loaded.manufacturerPolicy);
    setMarketing(loaded.marketing);
    setStaff(loaded.staff);
    setAfterSales(loaded.afterSales);
    setUsedCarShowroom(loaded.usedCarShowroom);
    setUsedCars(loaded.usedCars);
    setTestDriveCars(loaded.testDriveCars);
    setCsi(loaded.csi);
    setCustomerLifecycle(loaded.customerLifecycle);
    setInsuranceRenewals(loaded.insuranceRenewals);
    setSoldVehicles(loaded.soldVehicles);
    setMonthlyStats(loaded.monthlyStats);
    setOperatingEvents(loaded.operatingEvents);
    setFacility(loaded.facility);
    setInventory(loaded.inventory);
    setPendingOrders(loaded.pendingOrders);
    setDailyStats(loaded.dailyStats);
    setDailyLedger(loaded.dailyLedger);
    setApprovalCases(loaded.approvalCases);
    setCustomerDeals(loaded.customerDeals);
    setSalesOpportunities(loaded.salesOpportunities);
    setFeedback(loaded.feedback);
    setStoryState(loaded.storyState);
    setStaffStoryMemory(loaded.staffStoryMemory);
    setManagerInbox(loaded.managerInbox);
    setLogs(loaded.logs);
  };

  const resetAfterLoadUi = () => {
    setOrderForm(createInitialOrderForm());
    setSelectedLogDay(null);
    setSelectedInboxDay(null);
    setInboxFilter({ type: 'all', dayRange: 'all', specificDay: '' });
    setReadInboxIds(new Set());
    setExpandedInboxIds(new Set());
    setShowBriefingModal(false);
    setShowInboxModal(false);
    setMonthlySummaryModal(null);
    setActiveTab('dashboard');
    setFinanceReportView('profit');
  };

  return {
    applySaveData,
    buildSaveData,
    resetAfterLoadUi,
  };
}
