import { calculateNetAssets } from '../engine/scenarioEnding.js';
import { APP_VERSION_INFO } from '../config/appVersion.js';

export const buildAutoSaveGameState = ({
  dismissedByInvestor,
  isFreeScenario,
  absoluteDay,
  scenarioDurationDays,
  gameState,
  finance,
  activeScenario,
  investorRelations,
  feedback,
  assetContext,
}) => {
  if (dismissedByInvestor) return 'dismissed';
  if (!isFreeScenario && absoluteDay >= scenarioDurationDays && gameState !== 'bankrupt') {
    const { netAssets } = calculateNetAssets(assetContext);
    const excellentMonths = (feedback.ratingHistory || []).filter(item => (item.score || 0) >= 82 || (item.investorScore || 0) >= 82).length;
    const scenarioPassed = activeScenario.id === 'survive6'
      ? netAssets >= activeScenario.targetNetAssets * 0.75 && investorRelations.badReviews < 3
      : activeScenario.id === 'star12'
      ? netAssets >= activeScenario.targetNetAssets && excellentMonths >= (activeScenario.minExcellentMonths || 3)
      : netAssets >= activeScenario.targetNetAssets;
    return scenarioPassed ? 'won' : 'dismissed';
  }
  return finance.loan > finance.creditLimit ? 'bankrupt' : gameState;
};

export const buildAutoSaveData = ({
  savedAt = new Date().toLocaleString('zh-CN') + ' (自动)',
  gameState,
  day,
  dealerRegionId,
  marketSizeId,
  investorProfileId,
  investorRelations,
  finance,
  drafts,
  gmWealth,
  virtualSales,
  competitors,
  strategy,
  marketPrices,
  modelPriceOverrides,
  marketEnvironment,
  manufacturerPolicy,
  marketing,
  staff,
  afterSales,
  usedCarShowroom,
  usedCars,
  testDriveCars,
  csi,
  customerLifecycle,
  insuranceRenewals,
  soldVehicles,
  monthlyStats,
  operatingEvents,
  facility,
  inventory,
  pendingOrders,
  dailyStats,
  dailyLedger,
  managerInbox,
  approvalCases,
  customerDeals,
  salesOpportunities,
  feedback,
  storyState,
  staffStoryMemory,
  difficultyMode,
  scenarioId,
  tutorial,
  endingSummary,
  logs,
}) => ({
  version: APP_VERSION_INFO.saveSchemaVersion,
  savedAt,
  slotName: '自动存档',
  gameState,
  day,
  dealerRegionId,
  marketSizeId,
  investorProfileId,
  investorRelations,
  finance,
  drafts,
  gmWealth,
  virtualSales,
  competitors,
  strategy,
  marketPrices,
  modelPriceOverrides,
  marketEnvironment,
  manufacturerPolicy,
  marketing,
  staff,
  afterSales,
  usedCarShowroom,
  usedCars,
  testDriveCars,
  csi,
  customerLifecycle,
  insuranceRenewals,
  soldVehicles,
  monthlyStats,
  operatingEvents,
  facility,
  inventory,
  pendingOrders,
  dailyStats,
  dailyLedger,
  managerInbox,
  approvalCases,
  customerDeals,
  salesOpportunities,
  feedback,
  storyState,
  staffStoryMemory,
  difficultyMode,
  scenarioId,
  tutorial,
  endingSummary,
  logs,
});
