import { lazy, Suspense, useEffect } from 'react';
import { buildPlayingShellContext } from './app/buildPlayingShellContext.js';
import { buildCompetitorVisibility } from './app/competitorVisibility.js';
import { PlayingGameShell } from './app/PlayingGameShell.jsx';
import { useAfterSalesTechActions } from './app/useAfterSalesTechActions.js';
import { useAiActions } from './app/useAiActions.js';
import { useAppDerivedHelpers } from './app/useAppDerivedHelpers.js';
import { useBusinessState } from './app/useBusinessState.js';
import { useCaseActions } from './app/useCaseActions.js';
import { useCaseFactories } from './app/useCaseFactories.js';
import { useCaseState } from './app/useCaseState.js';
import { useCoreGameState } from './app/useCoreGameState.js';
import { useCsiActions } from './app/useCsiActions.js';
import { useCustomerLifecycleActions } from './app/useCustomerLifecycleActions.js';
import { useCustomerLifecycleState } from './app/useCustomerLifecycleState.js';
import { useDailyAdvanceController } from './app/useDailyAdvanceController.js';
import { useDailyLedgerState } from './app/useDailyLedgerState.js';
import { useFacilityActions } from './app/useFacilityActions.js';
import { useFinanceActions } from './app/useFinanceActions.js';
import { useFinanceState } from './app/useFinanceState.js';
import { useGameSetupActions } from './app/useGameSetupActions.js';
import { useInboxController } from './app/useInboxController.js';
import { useInventoryActions } from './app/useInventoryActions.js';
import { useInventoryState } from './app/useInventoryState.js';
import { useCompetitorIntelActions } from './app/useCompetitorIntelActions.js';
import { useManufacturerInteractionActions } from './app/useManufacturerInteractionActions.js';
import { useMarketingActions } from './app/useMarketingActions.js';
import { useMarketState } from './app/useMarketState.js';
import { useModalController } from './app/useModalController.js';
import { useNarrativeState } from './app/useNarrativeState.js';
import { useOperationalMetrics } from './app/useOperationalMetrics.js';
import { useOperatingEventActions } from './app/useOperatingEventActions.js';
import { usePlayingViewModel } from './app/usePlayingViewModel.js';
import { usePurchaseOrderActions } from './app/usePurchaseOrderActions.js';
import { useRestartActions } from './app/useRestartActions.js';
import { useSalesOpportunityActions } from './app/useSalesOpportunityActions.js';
import { useSaveDataBridge } from './app/useSaveDataBridge.js';
import { useSaveSlotController } from './app/useSaveSlotController.js';
import { useSettingsController } from './app/useSettingsController.js';
import { useStaffActions } from './app/useStaffActions.js';
import { useStaffState } from './app/useStaffState.js';
import { useStoryInboxActions } from './app/useStoryInboxActions.js';
import { useUiState } from './app/useUiState.js';
import { useUsedCarActions } from './app/useUsedCarActions.js';
import { useUsedCarState } from './app/useUsedCarState.js';
import { buildBusinessIntelligenceSnapshot } from './game/engine/businessIntelligence.js';
import { addMonthsToGameDate } from './game/engine/gameDate.js';
import { buildManufacturerInteractionSnapshot } from './game/engine/manufacturerNegotiation.js';
import {
  createInitialStoryState,
  createInitialStaffStoryMemory,
} from './game/state/initialState.js';

const SetupScreen = lazy(() => import('./features/setup/SetupScreen.jsx').then(module => ({ default: module.SetupScreen })));

function SetupLoadingFallback() {
  return (
    <div className="min-h-screen bg-slate-950 text-white p-8 flex items-center justify-center">
      <div className="rounded-2xl border border-white/10 bg-white/5 px-5 py-4 text-sm font-black text-slate-300">
        正在准备开局...
      </div>
    </div>
  );
}

export default function App() {
  const {
    activeDifficulty,
    activeInvestor,
    activeMarketSize,
    activeRegion,
    activeScenario,
    day,
    dayOfMonth,
    dealerRegionId,
    difficultyMode,
    endingModalDismissed,
    endingSummary,
    gameState,
    investorProfileId,
    isFreeScenario,
    month,
    scenarioDurationDays,
    scenarioId,
    setDay,
    setDealerRegionId,
    setDifficultyMode,
    setEndingModalDismissed,
    setEndingSummary,
    setGameState,
    setInvestorProfileId,
    setMarketSizeId,
    setScenarioId,
    setTutorial,
    tutorial,
  } = useCoreGameState();
  const {
    drafts,
    finance,
    gmWealth,
    setDrafts,
    setFinance,
    setGmWealth,
    setVirtualSales,
    virtualSales,
  } = useFinanceState();

  const {
    facility,
    feedback,
    investorRelations,
    monthlyStats,
    orderForm,
    operatingEvents,
    setFacility,
    setFeedback,
    setInvestorRelations,
    setMonthlyStats,
    setOrderForm,
    setOperatingEvents,
    setStrategy,
    strategy,
  } = useBusinessState();

  const { modalConfig, showAlert, showConfirm, closeModal } = useModalController();
  const {
    activeTab,
    financeReportView,
    isAdvancingDay,
    monthlySummaryModal,
    selectedLogDay,
    setActiveTab,
    setFinanceReportView,
    setIsAdvancingDay,
    setMonthlySummaryModal,
    setSelectedLogDay,
    setShowBriefingModal,
    setShowInboxModal,
    setVirtualPlan,
    showBriefingModal,
    showInboxModal,
    virtualPlan,
  } = useUiState();

  useEffect(() => {
    if (gameState !== 'playing' || !activeTab) return;
    setTutorial(prev => {
      const visitedTabs = Array.isArray(prev.visitedTabs) ? prev.visitedTabs : [];
      if (visitedTabs.includes(activeTab)) return prev;
      return { ...prev, visitedTabs: [...visitedTabs, activeTab].slice(-24) };
    });
  }, [activeTab, gameState, setTutorial]);

  const {
    carModels,
    competitors,
    getConfiguredModelPrice,
    getDynamicMsrp,
    getDynamicRebate,
    manufacturerPolicy,
    marketEnvironment,
    marketPrices,
    marketing,
    modelPriceOverrides,
    setCompetitors,
    setManufacturerPolicy,
    setMarketEnvironment,
    setMarketPrices,
    setMarketing,
    setModelPriceOverrides,
  } = useMarketState({ activeMarketSize });
  const { staff, setStaff } = useStaffState();

  const {
    afterSales,
    csi,
    customerLifecycle,
    insuranceRenewals,
    setAfterSales,
    setCsi,
    setCustomerLifecycle,
    setInsuranceRenewals,
    setSoldVehicles,
    soldVehicles,
  } = useCustomerLifecycleState();

  const { setUsedCars, setUsedCarShowroom, usedCars, usedCarShowroom } = useUsedCarState();

  const {
    inventory,
    pendingOrders,
    setInventory,
    setPendingOrders,
    setTestDriveCars,
    testDriveCars,
  } = useInventoryState();

  const {
    dccAvgSkill,
    dccCount,
    estimateDealAddons,
    getActiveCountermeasureValue,
    getCompetitorPressure,
    getPriceReality,
    getRetailQualityScore,
    leadChannels,
    salesAvgSkill,
    salesCount,
    serviceAvgSkill,
    serviceCount,
    streamerAvgSkill,
    streamerCount,
    techAvgSkill,
    techCount,
    totalLeadPool,
  } = useOperationalMetrics({
    afterSales,
    competitors,
    csi,
    getDynamicMsrp,
    getDynamicRebate,
    marketing,
    staff,
  });

  const { appendLedger, dailyLedger, dailyStats, setDailyLedger, setDailyStats } = useDailyLedgerState({ currentDay: day });
  const {
    addLog,
    logs,
    managerInbox,
    setLogs,
    setManagerInbox,
    setStaffStoryMemory,
    setStoryState,
    staffStoryMemory,
    storyState,
  } = useNarrativeState({ currentDay: day });
  const {
    approvalCases,
    customerDeals,
    salesOpportunities,
    setApprovalCases,
    setCustomerDeals,
    setSalesOpportunities,
  } = useCaseState();
  
  const {
    selectedInboxDay,
    setSelectedInboxDay,
    inboxFilter,
    setInboxFilter,
    readInboxIds,
    setReadInboxIds,
    expandedInboxIds,
    setExpandedInboxIds,
    expandedMessageIds,
    toggleInboxRead,
    toggleExpandedInbox,
    toggleExpandedMessage,
    openInboxForDay: openInboxForDayBase,
    filteredInboxMessages,
    unreadInboxCount,
  } = useInboxController({ managerInbox, currentDay: day });
  const openInboxForDay = (targetDay = null) => {
    openInboxForDayBase(targetDay);
    setShowInboxModal(true);
  };

  const { handleResolveStoryAction } = useStoryInboxActions({
    storyState,
    setStoryState,
    setManagerInbox,
    setLogs,
    setReadInboxIds,
    currentDay: day,
  });
  
  const {
    buildFeedbackState,
    financeSnapshot,
    formatMoney,
    getAvailableDraftCredit,
    getCompanyDailyBurn,
    getDraftFeeRate,
    getDraftRemainingDays,
  } = useAppDerivedHelpers({
    afterSales,
    carModels,
    csi,
    dailyLedger,
    day,
    drafts,
    facility,
    feedback,
    finance,
    gmWealth,
    inventory,
    investorRelations,
    marketing,
    month,
    monthlyStats,
    soldVehicles,
    staff,
    usedCars,
    virtualSales,
  });
  const {
    createComplaintCase,
    createCustomerDealCase,
    createPriceApprovalCase,
  } = useCaseFactories({
    activeRegion,
    currentDay: day,
    csi,
    estimateDealAddons,
    getPriceReality,
    getRetailQualityScore,
    inventory,
    marketPrices,
    salesAvgSkill,
  });

  const {
    startNewGame,
  } = useGameSetupActions({
    activeDifficulty,
    activeInvestor,
    activeMarketSize,
    activeRegion,
    activeScenario,
    formatMoney,
    setCompetitors,
    setCsi,
    setCustomerLifecycle,
    setEndingModalDismissed,
    setEndingSummary,
    setFeedback,
    setFinance,
    setGameState,
    setLogs,
    setManagerInbox,
    setMarketEnvironment,
    setMarketPrices,
    setMonthlyStats,
    setOperatingEvents,
    setSalesOpportunities,
    setStoryState,
    setStaffStoryMemory,
    setTutorial,
    createInitialStoryState,
    createInitialStaffStoryMemory,
  });

  const { handleNextDay } = useDailyAdvanceController({
    activeDifficulty,
    activeInvestor,
    activeMarketSize,
    activeRegion,
    activeScenario,
    afterSales,
    approvalCases,
    buildFeedbackState,
    createComplaintCase,
    createCustomerDealCase,
    createPriceApprovalCase,
    competitors,
    csi,
    customerLifecycle,
    customerDeals,
    salesOpportunities,
    dailyLedger,
    day,
    dayOfMonth,
    dealerRegionId,
    dccAvgSkill,
    dccCount,
    difficultyMode,
    drafts,
    endingSummary,
    facility,
    feedback,
    finance,
    formatMoney,
    gameState,
    getActiveCountermeasureValue,
    getCompanyDailyBurn,
    getCompetitorPressure,
    getConfiguredModelPrice,
    getDynamicMsrp,
    getDynamicRebate,
    getPriceReality,
    getSaveSlots: (...args) => getSaveSlots(...args),
    gmWealth,
    inventory,
    insuranceRenewals,
    investorProfileId,
    investorRelations,
    isAdvancingDay,
    isFreeScenario,
    logs,
    managerInbox,
    manufacturerPolicy,
    marketEnvironment,
    marketPrices,
    marketing,
    modelPriceOverrides,
    month,
    monthlyStats,
    operatingEvents,
    pendingOrders,
    salesAvgSkill,
    salesCount,
    scenarioDurationDays,
    scenarioId,
    serviceAvgSkill,
    serviceCount,
    setAfterSales,
    setApprovalCases,
    setCompetitors,
    setCsi,
    setCustomerLifecycle,
    setCustomerDeals,
    setSalesOpportunities,
    setDailyLedger,
    setDailyStats,
    setDay,
    setDrafts,
    setEndingModalDismissed,
    setEndingSummary,
    setFeedback,
    setFinance,
    setGameState,
    setGmWealth,
    setInsuranceRenewals,
    setInventory,
    setInvestorRelations,
    setIsAdvancingDay,
    setLogs,
    setManagerInbox,
    setManufacturerPolicy,
    setMarketEnvironment,
    setMarketing,
    setMarketPrices,
    setMonthlyStats,
    setOperatingEvents,
    setMonthlySummaryModal,
    setPendingOrders,
    setSoldVehicles,
    setStoryState,
    setStaffStoryMemory,
    setStaff,
    setUsedCars,
    setVirtualSales,
    soldVehicles,
    storyState,
    staffStoryMemory,
    staff,
    strategy,
    streamerAvgSkill,
    streamerCount,
    techAvgSkill,
    techCount,
    testDriveCars,
    tutorial,
    usedCarShowroom,
    usedCars,
    virtualSales,
  });
  const { handleResolveOperatingEvent } = useOperatingEventActions({
    activeDifficulty,
    appendLedger,
    csi,
    currentDay: day,
    finance,
    formatMoney,
    marketing,
    monthlyStats,
    operatingEvents,
    setCsi,
    setFinance,
    setLogs,
    setManagerInbox,
    setMarketing,
    setMonthlyStats,
    setOperatingEvents,
    showAlert,
  });
  const {
    netProfit,
    activeDraftList,
    unpaidDraftAmount,
    nearestDraft,
    warningDrafts,
    defaultedDrafts,
    draftCreditUsage,
    cashCoverageDays,
    balanceAssets,
    balanceLiabilities,
    ownerEquity,
  } = financeSnapshot;
  const businessIntelligence = buildBusinessIntelligenceSnapshot({
    monthlyStats,
    finance,
    financeSnapshot,
    inventory,
    pendingOrders,
    usedCars,
    csi,
    customerLifecycle,
    customerDeals,
    salesOpportunities,
    soldVehicles,
    carModels,
    manufacturerPolicy,
    competitors,
    marketEnvironment,
    activeRegion,
    feedback,
    dayOfMonth,
    month,
  });
  const manufacturerInteraction = buildManufacturerInteractionSnapshot({
    manufacturerPolicy,
    monthlyStats,
    finance,
    inventory,
    csi,
    virtualSales,
    modelPriceOverrides,
    carModels,
    marketEnvironment,
    dayOfMonth,
    month,
    activeDifficulty,
  });
  const {
    handleApplySubsidy,
    handleApplySeriesPriceStrategy,
    handleAutoShowroom,
    handleMoveCar,
    handlePriceBlur,
    handleRetireTestDrive,
    handleSetTestDrive,
    handleUpdatePrice,
    handleWholesale,
  } = useInventoryActions({
    addLog,
    appendLedger,
    carModels,
    currentDay: day,
    facility,
    finance,
    formatMoney,
    getConfiguredModelPrice,
    getDynamicMsrp,
    inventory,
    marketPrices,
    monthlyStats,
    setDailyLedger,
    setFinance,
    setInventory,
    setModelPriceOverrides,
    setMonthlyStats,
    setTestDriveCars,
    showAlert,
    showConfirm,
    testDriveCars,
  });
  const {
    handleBuildShowroom,
    handlePrepUsedCar,
    handleUpgradeShowroom,
    handleUsedCarPriceChange,
    handleUsedCarRetail,
    handleUsedCarWholesale,
  } = useUsedCarActions({
    addLog,
    appendLedger,
    finance,
    monthlyStats,
    setFinance,
    setMonthlyStats,
    setUsedCars,
    setUsedCarShowroom,
    showAlert,
    showConfirm,
    usedCars,
    usedCarShowroom,
  });
  const {
    handleHireTech,
    handleTrainTech,
    toggleTechRetention,
  } = useAfterSalesTechActions({
    addLog,
    afterSales,
    appendLedger,
    finance,
    setAfterSales,
    setFinance,
    showAlert,
    showConfirm,
  });
  const {
    hireStaff,
    toggleRetention,
    trainMember,
  } = useStaffActions({
    addLog,
    appendLedger,
    finance,
    formatMoney,
    setFinance,
    setStaff,
    showAlert,
    showConfirm,
    staff,
  });
  const {
    launchActivity,
  } = useMarketingActions({
    addLog,
    appendLedger,
    currentDay: day,
    finance,
    marketing,
    monthlyStats,
    setFinance,
    setMarketing,
    setMonthlyStats,
    showAlert,
    showConfirm,
  });
  const {
    upgradeFacility,
  } = useFacilityActions({
    addLog,
    appendLedger,
    facility,
    finance,
    setFacility,
    setFinance,
    showAlert,
    showConfirm,
  });
  const {
    handleAdjustGmSalary,
    handleCompetitorCountermeasure,
    handleManualRepayLoan,
    handlePersonalBailout,
    handleRepayOverdueDraft,
    handleStrategyChange,
    handleVirtualSprint,
  } = useFinanceActions({
    addLog,
    appendLedger,
    competitors,
    currentDay: day,
    dayOfMonth,
    drafts,
    finance,
    formatMoney,
    getDynamicMsrp,
    getDynamicRebate,
    gmWealth,
    inventory,
    month,
    monthlyStats,
    setCompetitors,
    setDrafts,
    setFinance,
    setGmWealth,
    setInventory,
    setMonthlyStats,
    setStrategy,
    setVirtualPlan,
    setVirtualSales,
    showAlert,
    showConfirm,
    strategy,
    virtualPlan,
    virtualSales,
  });
  const {
    handleCompetitorIntelAction,
  } = useCompetitorIntelActions({
    activeDifficulty,
    addLog,
    appendLedger,
    competitors,
    dayOfMonth,
    finance,
    formatMoney,
    month,
    setCompetitors,
    setFinance,
    showAlert,
    showConfirm,
  });
  const {
    handleComplaintResolution,
    handleCustomerDeal,
    handlePriceApproval,
    openNegotiation,
    resolveNegotiation,
  } = useCaseActions({
    activeInvestor,
    activeRegion,
    addLog,
    approvalCases,
    appendLedger,
    csi,
    competitors,
    currentDay: day,
    customerDeals,
    dailyStats,
    dayOfMonth,
    estimateDealAddons,
    finance,
    formatMoney,
    getPriceReality,
    inventory,
    investorRelations,
    marketing,
    monthlyStats,
    month,
    netProfit,
    setApprovalCases,
    setCompetitors,
    setCsi,
    setCustomerLifecycle,
    setCustomerDeals,
    setDailyStats,
    setFinance,
    setInventory,
    setInvestorRelations,
    setMarketing,
    setMonthlyStats,
    setSoldVehicles,
    setUsedCars,
    showAlert,
    soldVehicles,
    usedCars,
  });
  const { handleCustomerFollowUp } = useCustomerLifecycleActions({
    activeDifficulty,
    appendLedger,
    csi,
    customerLifecycle,
    currentDay: day,
    finance,
    formatMoney,
    insuranceRenewals,
    marketing,
    monthlyStats,
    setCsi,
    setCustomerLifecycle,
    setFinance,
    setInsuranceRenewals,
    setLogs,
    setMarketing,
    setMonthlyStats,
    showAlert,
  });
  const { handleSalesOpportunityAction } = useSalesOpportunityActions({
    activeDifficulty,
    activeRegion,
    appendLedger,
    csi,
    currentDay: day,
    createCustomerDealCase,
    estimateDealAddons,
    formatMoney,
    getPriceReality,
    getRetailQualityScore,
    inventory,
    marketPrices,
    salesAvgSkill,
    salesOpportunities,
    staff,
    setCustomerDeals,
    setFinance,
    setLogs,
    setManagerInbox,
    setMonthlyStats,
    setSalesOpportunities,
    setStaff,
    showAlert,
  });
  const {
    aiAdCopy,
    aiAdvice,
    handleAskAIConsultant,
    handleGenerateAIAd,
    isGeneratingAd,
    isGeneratingAdvice,
  } = useAiActions({
    addLog,
    appendLedger,
    dayOfMonth,
    finance,
    inventory,
    monthlyStats,
    setFinance,
    setMarketing,
    showAlert,
    showConfirm,
  });
  const {
    executeOrder,
  } = usePurchaseOrderActions({
    addLog,
    addMonthsToGameDate,
    appendLedger,
    currentDay: day,
    dayOfMonth,
    drafts,
    facility,
    finance,
    formatMoney,
    getDraftFeeRate,
    inventory,
    investorRelations,
    marketEnvironment,
    manufacturerPolicy,
    month,
    monthlyStats,
    orderForm,
    pendingOrders,
    setDrafts,
    setFinance,
    setManufacturerPolicy,
    setMonthlyStats,
    setOrderForm,
    setPendingOrders,
    showAlert,
  });
  const {
    handleManufacturerResourceRequest,
  } = useManufacturerInteractionActions({
    activeDifficulty,
    addLog,
    appendLedger,
    carModels,
    csi,
    currentDay: day,
    dayOfMonth,
    finance,
    formatMoney,
    inventory,
    manufacturerPolicy,
    marketEnvironment,
    modelPriceOverrides,
    month,
    monthlyStats,
    setFinance,
    setManufacturerPolicy,
    setMonthlyStats,
    showAlert,
    virtualSales,
  });
  const {
    handleCsiCareAction,
    handleCsiFollowUpAction,
  } = useCsiActions({
    addLog,
    appendLedger,
    finance,
    setCsi,
    setFinance,
    showAlert,
  });

  const { handleRestart } = useRestartActions({ showConfirm });

  const {
    applySaveData,
    buildSaveData,
    resetAfterLoadUi,
  } = useSaveDataBridge({
    activeMarketSize,
    afterSales,
    approvalCases,
    competitors,
    csi,
    customerLifecycle,
    customerDeals,
    salesOpportunities,
    dailyLedger,
    dailyStats,
    day,
    dealerRegionId,
    difficultyMode,
    drafts,
    endingSummary,
    facility,
    feedback,
    finance,
    gameState,
    gmWealth,
    insuranceRenewals,
    inventory,
    investorProfileId,
    investorRelations,
    logs,
    managerInbox,
    manufacturerPolicy,
    marketEnvironment,
    marketPrices,
    marketing,
    modelPriceOverrides,
    monthlyStats,
    operatingEvents,
    pendingOrders,
    scenarioId,
    setActiveTab,
    setAfterSales,
    setApprovalCases,
    setCompetitors,
    setCsi,
    setCustomerLifecycle,
    setCustomerDeals,
    setSalesOpportunities,
    setDailyLedger,
    setDailyStats,
    setDay,
    setDealerRegionId,
    setDifficultyMode,
    setDrafts,
    setEndingModalDismissed,
    setEndingSummary,
    setExpandedInboxIds,
    setFacility,
    setFeedback,
    setFinance,
    setFinanceReportView,
    setGameState,
    setGmWealth,
    setInboxFilter,
    setInsuranceRenewals,
    setInventory,
    setInvestorProfileId,
    setInvestorRelations,
    setLogs,
    setManagerInbox,
    setManufacturerPolicy,
    setMarketEnvironment,
    setMarketPrices,
    setMarketSizeId,
    setMarketing,
    setModelPriceOverrides,
    setMonthlyStats,
    setMonthlySummaryModal,
    setOrderForm,
    setOperatingEvents,
    setPendingOrders,
    setReadInboxIds,
    setScenarioId,
    setSelectedInboxDay,
    setSelectedLogDay,
    setShowBriefingModal,
    setShowInboxModal,
    setSoldVehicles,
    setStoryState,
    setStaffStoryMemory,
    setStaff,
    setStrategy,
    setTestDriveCars,
    setTutorial,
    setUsedCars,
    setUsedCarShowroom,
    setVirtualSales,
    soldVehicles,
    storyState,
    staffStoryMemory,
    staff,
    strategy,
    testDriveCars,
    tutorial,
    usedCars,
    usedCarShowroom,
    virtualSales,
  });

  const {
    showSaveModal,
    setShowSaveModal,
    showLoadModal,
    setShowLoadModal,
    setLoadStartedFromSetup,
    renameSlot,
    setRenameSlot,
    renameValue,
    setRenameValue,
    getSaveSlots,
    getLoadSlotEntries,
    handleSaveToSlot,
    closeLoadModal,
    handleLoadFromSlot,
    handleDeleteSlot,
    handleRenameSlot,
    hasAnySaveData,
  } = useSaveSlotController({
    buildSaveData,
    applySaveData,
    resetAfterLoadUi,
    showAlert,
    showConfirm,
    currentDay: day,
    onReturnToSetup: () => setGameState('setup'),
  });

  const settingsController = useSettingsController({
    applySaveData,
    buildSaveData,
    getSaveSlots,
    resetAfterLoadUi,
    showAlert,
    showConfirm,
  });

  const { hiddenCompetitorCount, visibleCompetitorStores } = buildCompetitorVisibility(competitors);
  const {
    activeGroup,
    activeTutorialStep,
    briefingMetrics,
    convertRateVal,
    currentEnding,
    currentLossDrivers,
    dailyChecklist,
    endingMeta,
    excellentMonthCount,
    feedbackState,
    getRatingMeta,
    hasProfitSample,
    inviteRateVal,
    latestBadges,
    marketShareSegments,
    messageFeed,
    moduleGroups,
    normalizedMarketShare,
    onboardingTraining,
    openTaskTarget,
    operatingRating,
    operatingScore,
    pendingApprovalCases,
    scenarioProgress,
    targetProgress,
    todoQueue,
    unlockedAchievements,
    urgentOperationCount,
    visibleMessageFeed,
  } = usePlayingViewModel({
    activeDifficulty,
    activeScenario,
    activeTab,
    approvalCases,
    balanceAssets,
    balanceLiabilities,
    competitors,
    csi,
    currentDay: day,
    customerDeals,
    salesOpportunities,
    dccCount,
    defaultedDrafts,
    dayOfMonth,
    endingModalDismissed,
    endingSummary,
    facility,
    feedback,
    finance,
    formatMoney,
    gameState,
    inventory,
    isFreeScenario,
    logs,
    managerInbox,
    marketEnvironment,
    month,
    monthlyStats,
    netProfit,
    ownerEquity,
    pendingOrders,
    salesCount,
    scenarioDurationDays,
    setActiveTab,
    soldVehicles,
    totalLeadPool,
    tutorial,
    usedCars,
    usedCarShowroom,
  });

  if (gameState === 'setup') {
    return (
      <Suspense fallback={<SetupLoadingFallback />}>
        <SetupScreen
          dealerRegionId={dealerRegionId}
          setDealerRegionId={setDealerRegionId}
          setMarketSizeId={setMarketSizeId}
          investorProfileId={investorProfileId}
          setInvestorProfileId={setInvestorProfileId}
          difficultyMode={difficultyMode}
          setDifficultyMode={setDifficultyMode}
          scenarioId={scenarioId}
          setScenarioId={setScenarioId}
          activeMarketSize={activeMarketSize}
          activeRegion={activeRegion}
          activeInvestor={activeInvestor}
          activeDifficulty={activeDifficulty}
          activeScenario={activeScenario}
          hasAnySaveData={hasAnySaveData()}
          onLoadSave={() => {
            setLoadStartedFromSetup(true);
            setGameState('playing');
            setShowLoadModal(true);
          }}
          onStartNewGame={startNewGame}
          formatMoney={formatMoney}
        />
      </Suspense>
    );
  }

  const shellContext = buildPlayingShellContext({
    state: {
    activeDifficulty,
    activeInvestor,
    activeRegion,
    activeScenario,
    activeTab,
    afterSales,
    aiAdCopy,
    aiAdvice,
    carModels,
    competitors,
    csi,
    customerLifecycle,
    customerDeals,
    dailyLedger,
    day,
    dayOfMonth,
    drafts,
    dccCount,
    expandedInboxIds,
    expandedMessageIds,
    facility,
    filteredInboxMessages,
    finance,
    financeReportView,
    financeSnapshot,
    gameState,
    gmWealth,
    inboxFilter,
    insuranceRenewals,
    inventory,
    investorRelations,
    isAdvancingDay,
    isFreeScenario,
    isGeneratingAd,
    isGeneratingAdvice,
    leadChannels,
    logs,
    managerInbox,
    manufacturerPolicy,
    marketEnvironment,
    marketPrices,
    marketing,
    modalConfig,
    month,
    monthlyStats,
    monthlySummaryModal,
    orderForm,
    pendingOrders,
    readInboxIds,
    renameSlot,
    renameValue,
    selectedInboxDay,
    selectedLogDay,
    serviceAvgSkill,
    serviceCount,
    showBriefingModal,
    showInboxModal,
    showLoadModal,
    showSaveModal,
    staff,
    staffStoryMemory,
    storyState,
    strategy,
    techAvgSkill,
    techCount,
    testDriveCars,
    tutorial,
    usedCars,
    usedCarShowroom,
    virtualPlan,
    virtualSales,
    },
    actions: {
    closeLoadModal,
    closeModal,
    executeOrder,
    handleAdjustGmSalary,
    handleApplySeriesPriceStrategy,
    handleAskAIConsultant,
    handleAutoShowroom,
    handleBuildShowroom,
    handleApplySubsidy,
    handleCsiCareAction,
    handleCsiFollowUpAction,
    handleCustomerDeal,
    handleCustomerFollowUp,
    handleSalesOpportunityAction,
    handleComplaintResolution,
    handleCompetitorCountermeasure,
    handleCompetitorIntelAction,
    handleDeleteSlot,
    handleGenerateAIAd,
    handleHireTech,
    handleLoadFromSlot,
    handleManualRepayLoan,
    handleManufacturerResourceRequest,
    handleMoveCar,
    handleNextDay,
    handlePersonalBailout,
    handlePrepUsedCar,
    handlePriceApproval,
    handlePriceBlur,
    handleRenameSlot,
    handleRepayOverdueDraft,
    handleRestart,
    handleResolveOperatingEvent,
    handleRetireTestDrive,
    handleResolveStoryAction,
    handleSaveToSlot,
    handleSetTestDrive,
    handleStrategyChange,
    handleTrainTech,
    handleUpdatePrice,
    handleUpgradeShowroom,
    handleUsedCarPriceChange,
    handleUsedCarRetail,
    handleUsedCarWholesale,
    handleVirtualSprint,
    handleWholesale,
    hireStaff,
    launchActivity,
    openInboxForDay,
    openNegotiation,
    resolveNegotiation,
    setActiveTab,
    setEndingModalDismissed,
    setExpandedInboxIds,
    setFinanceReportView,
    setInboxFilter,
    setMarketing,
    setMonthlySummaryModal,
    setOrderForm,
    setRenameSlot,
    setRenameValue,
    setSelectedInboxDay,
    setSelectedLogDay,
    setShowBriefingModal,
    setShowInboxModal,
    setShowLoadModal,
    setShowSaveModal,
    setTutorial,
    setVirtualPlan,
    toggleExpandedInbox,
    toggleExpandedMessage,
    toggleInboxRead,
    toggleRetention,
    toggleTechRetention,
    trainMember,
    upgradeFacility,
    },
    selectors: {
    activeDraftList,
    activeGroup,
    activeTutorialStep,
    balanceAssets,
    balanceLiabilities,
    briefingMetrics,
    businessIntelligence,
    manufacturerInteraction,
    cashCoverageDays,
    convertRateVal,
    currentEnding,
    currentLossDrivers,
    dailyChecklist,
    defaultedDrafts,
    draftCreditUsage,
    endingMeta,
    excellentMonthCount,
    estimateDealAddons,
    feedbackState,
    formatMoney,
    getAvailableDraftCredit,
    getDraftFeeRate,
    getDraftRemainingDays,
    getDynamicMsrp,
    getDynamicRebate,
    getLoadSlotEntries,
    getRatingMeta,
    getSaveSlots,
    hasAnySaveData,
    hasProfitSample,
    hiddenCompetitorCount,
    inviteRateVal,
    latestBadges,
    marketShareSegments,
    messageFeed,
    moduleGroups,
    nearestDraft,
    netProfit,
    normalizedMarketShare,
    onboardingTraining,
    openTaskTarget,
    operatingRating,
    operatingScore,
    ownerEquity,
    pendingApprovalCases,
    salesCount,
    scenarioDurationDays,
    scenarioProgress,
    targetProgress,
    todoQueue,
    totalLeadPool,
    unreadInboxCount,
    unlockedAchievements,
    unpaidDraftAmount,
    urgentOperationCount,
    visibleCompetitorStores,
    visibleMessageFeed,
    warningDrafts,
    },
    ui: {
      settings: settingsController,
    },
  });

  return <PlayingGameShell context={shellContext} />;
}
